### ISSUE TITLE
Re-sizing the TOC

### ISSUE THREAD

**Issue by Hazz912** [teamrc/wikitoc#4]
If you click the arrow to re size the TOC smaller 5 times, then the TOC becomes too small to interact with and can be hard to expand back to its original size, the steps to replicate this issue are as follows -

1. Go to the Firefox wikipedia page with the extension enabled (http://en.wikipedia.org/wiki/Firefox)
2. On the left hand side of the page you should be able to see the TOC (Table of contents) In the top left of that section is a << button that resizes the window.
3. Press that 5 times and you will observe that the resolution has become too small to interact with, example shown here - (http://i.imgur.com/ulA8r9f.png)

System Specifications:

1920x1080 resolution
Windows 7
Firefox Browser

**Comment by teamrc** [comment]
This issue has already been fixed.
